### ISSUE TITLE
Gnome 42 support

### ISSUE THREAD

**Issue by nbenitez** [squgeim/Workspace-Scroll#10]
Currently the extension cannot be used in Gnome 42 (eg. Fedora 36).

Thanks for this useful extension :-)

**Comment by AlexWayfer** [comment]
GNOME 43 has been released.

@squgeim are you maintaining this extension still?

**Comment by squgeim** [comment]
I am sorry I have fallen behind on updating this extension. I no longer use Gnome on a daily basis. I'll try to squeeze in upgrading it this week. A PR is welcome as well 🙏.
