### ISSUE TITLE
Doesn't works anymore since the last update

### ISSUE THREAD

**Issue by lakano** [squgeim/Workspace-Scroll#2]
Hello!
Thanks for your useful extension! I uses it since 2 years :)
Since the last update, the extension doesn't works anymore.
I'm under Fedora 28, Gnome 3.28.2
I've seen someone else have commented for the same problem ( https://extensions.gnome.org/extension/943/workspace-scroll/ )
Could you please check for a bugfix please?

**Comment by squgeim** [comment]
I am sorry about this. This was caused by a recent change to support version 3.30. I have fixed the issues and submitted it. It will be released as soon as the review is complete.

Thanks for sticking to it for 2 years! I honestly didn't know there were any users.

**Comment by lakano** [comment]
Thanks for the quick answer!
I've tried to patch my ~/.local/share/gnome-shell/extensions/workspace_scroll@squgeim.com.np/extension.js to follow your last commit ( replace global.hasOwnProperty('screen') with global.screen ), and with Gnome Tweak to disable/enable the extension, but this doesn't seems to fix it.
So, I'm not sure the bug was really fixed for me :-/

**Comment by squgeim** [comment]
You might have to log out and log back in. Let me take a look at it once more.

**Comment by lakano** [comment]
Exact, this works :)
Thanks!
